//Escribir un programa que lea tres números e indique el tipo de
 //triángulo que forman (isósceles, equilatero, escaleno). 
 //Permitir que se pueda repetir indefinidamente si el usuario lo 
 //desea (que el ordenador pregunte ¿Quiere continuar? y la persona pueda responder S ó N) 

class EJERCICIO7
{

public int l1;
l1.imprimir()
public int l2;
l2.imprimir()
public int l3
l3.imprimir()
public int 1(si);
1.imprimir()
public int 2(no);
2.imprimir()


console.Writeline("Ingrese los lados del triángulo");

if (l1==l2){

       if (l2==l3){
               console.Writeline("Es un triangulo equilatero");
       }
        else {
           console.Writeline("Es un triangulo isòsceles");    
        }

}
else  if (l1==l3){
           console.Writeline("Es un triangulo isòsceles");

}

if ( l2==l3)
         console.Writeline("Es un triangulo isòsceles");

else {

console.Writeline("Es un triangulo escaleno");
while ( op==1){
console.Writeline("¿QUIERES VOLVER A EJECUTAR EL PROGRAMA?" escriba 1(si)o escriba 2(no));
op.imprimir()


}
}

return 0;
}