//Programa que lea una serie de números
// (leer hasta que llegue el cero por ejemplo) y que calcule su media aritmética 
class EJERCICIO9{
 pubic float= suma;
 float.imprimir()
 public int num:
 num.imprimir()
 pubic  int cont;
cont.imprimir()

while(num !=0)
{
console.Writeline("ingrese un numero");
this.num=num
suma=suma+num;
if(num!=0){
    cont=cont+1;
}

}

console.Writeline("La media  aritmetica es:" +suma/cont);


}